version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  search_web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=3005
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      # - ELASTICSEARCH_URL=http://elastic:password@search_db:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=password
    ports:
      - "3005:3005"
    depends_on:
      - elasticsearch
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
    driver: bridge