# version: '3'
# services:
#   search_db:
#     image: elasticsearch:8.12.2
#     volumes:
#       - ../db/leare_search_db:/elasticsearch/db/route
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: password
#     ports:
#       - "27017:27017"

#   search_web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3004:3004"
#     depends_on:
#       - search_db

version: '3'

services:
  search_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "ELASTIC_PASSWORD=password"
    ports:
      - "9200:9200"
    volumes:
      - ../db/leare_search_db:/usr/share/elasticsearch/data
    networks:
      - leare_network

  search_web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=3005
      - ELASTICSEARCH_URL=http://search_db:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=password
    ports:
      - "3005:3005"
    depends_on:
      - search_db
    networks:
      - leare_network

networks:
  leare_network:
    driver: bridge